apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- if .Values.app.labels }}
      {{- .Values.app.labels | toYaml | nindent 4 -}}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- if .Values.app.labels }}
        {{- .Values.app.labels | toYaml | nindent 6 -}}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if .Values.app.labels }}
          {{- .Values.app.labels | toYaml | nindent 8 -}}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - name: http
            containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.namespace }}
spec:
  type: LoadBalancer
  selector:
    {{- if .Values.app.labels }}
      {{- .Values.app.labels | toYaml | nindent 4 -}}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
