apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io/name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io/name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io/name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - name: http
            containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io/name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http