apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetapp-pepoc-test2
  namespace: development
  labels:
    app.kubernetes.io/name: tweetapp-pepoc-test2
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: tweetapp-pepoc-test2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tweetapp-pepoc-test2
    spec:
      containers:
      - name: tweetapp-pepoc-test2
        image: 960456129040.dkr.ecr.us-east-1.amazonaws.com/tweetapp2-pepoc-test2:latest
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
