apiVersion: v1
kind: Service
metadata:
  name: tweetapp-pepoc-test2
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tweetapp-pepoc-test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: http