apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io//name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http