app:
  name: tweetapp-pepoc-test2
labels:
  app:
    kubernetes_io_name: tweetapp-pepoc-test2
replicaCount: 5
image:
  repository: 960456129040.dkr.ecr.us-east-1.amazonaws.com/tweetapp2-pepoc-test2
  tag: latest
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
containerPort: 80
service:
  port: 80
namespace: development